# -*- coding: utf-8 -*-
"""castanha_1d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrU8sXxLjYlPBP1wRAtksOI_5y9dfaa5

## ETAPA 1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Carregando os dois arquivos
df_insumos = pd.read_csv("/content/insumos_PA.csv")
df_features = pd.read_csv("/content/features_PA.csv")

print("Insumos:", df_insumos.shape)
print("Features:", df_features.shape)

print (df_insumos ['1.3 - Castanha-do-pará'])

# Convertendo para formato longo (tidy)
df_long = df_insumos.melt(
    id_vars="Ano",
    var_name="insumo",
    value_name="prod_ton"
)

df_castanha = df_long[
    df_long["insumo"] == "1.3 - Castanha-do-pará"
].copy()

print("Shape castanha:", df_castanha.shape)

df_castanha.rename(
    columns={"Ano": "ano"},
    inplace=True
)

# Estatísticas descritivas da produção
desc_prod = df_castanha["prod_ton"].describe()
print(desc_prod)

# Estatísticas adicionais
media = df_castanha["prod_ton"].mean()
mediana = df_castanha["prod_ton"].median()
desvio = df_castanha["prod_ton"].std()
coef_var = desvio / media

print(f"Média: {media:.2f}")
print(f"Mediana: {mediana:.2f}")
print(f"Desvio padrão: {desvio:.2f}")
print(f"Coeficiente de variação: {coef_var:.2f}")

# PASSO 3.2
# Objetivo: Visualizar a distribuição da produção de castanha-do-Pará

plt.figure(figsize=(8, 5))
plt.hist(df_castanha["prod_ton"].dropna(), bins=15)
plt.xlabel("Produção (toneladas)")
plt.ylabel("Frequência")
plt.title("Histograma da Produção de Castanha-do-Pará (PA)")
plt.show()

# PASSO 3.3
# Objetivo: Identificar dispersão e outliers da produção

plt.figure(figsize=(6, 4))
plt.boxplot(df_castanha["prod_ton"].dropna(), vert=False)
plt.xlabel("Produção (toneladas)")
plt.title("Boxplot da Produção de Castanha-do-Pará (PA)")
plt.show()

# Convertendo coluna de data para datetime
df_features["Data"] = pd.to_datetime(df_features["Data"])

# Criando coluna de ano
df_features["ano"] = df_features["Data"].dt.year

print(df_features[["Data", "ano"]].head())

# Seleção de variáveis climáticas para agregação
variaveis_clima = [
    "Precipitacao_Media",
    "Temp_Max_Media",
    "Temp_Min_Media",
    "Umidade_Relativa_Media",
    "VPD_Medio",
    "Total_Focos",
    "Dias_Secos_Medio"
]

variaveis_clima = [v for v in variaveis_clima if v in df_features.columns]

# Convertendo colunas para tipo numérico, tratando erros
for col in variaveis_clima:
    if col in df_features.columns:
        df_features[col] = pd.to_numeric(df_features[col], errors='coerce')

# Agregação anual das variáveis climáticas
df_features_ano = (
    df_features
    .groupby("ano")[variaveis_clima]
    .mean()
    .reset_index()
)

print(df_features_ano.head())
print("Shape features anuais:", df_features_ano.shape)

# ANÁLISE MULTIDIMENSIONAL
 # Junção dos dados pelo ano
df_analise = pd.merge(df_castanha[['ano', 'prod_ton']], df_features_ano, on='ano')

# Visualizando as primeiras linhas do conjunto unificado
print("Shape do dataset unificado:", df_analise.shape)
df_analise.head()

# 1. Convertendo prod_ton e as variáveis climáticas para números (float)
# O parâmetro errors='coerce' transforma qualquer texto que não seja número em NaN (vazio)
df_analise['prod_ton'] = pd.to_numeric(df_analise['prod_ton'], errors='coerce')
df_analise['Precipitacao_Media'] = pd.to_numeric(df_analise['Precipitacao_Media'], errors='coerce')
df_analise['Temp_Max_Media'] = pd.to_numeric(df_analise['Temp_Max_Media'], errors='coerce')

# 2. Removendo linhas que ficaram com NaN após a conversão (opcional, mas evita erros no plot)
df_analise = df_analise.dropna(subset=['prod_ton', 'Precipitacao_Media', 'Temp_Max_Media'])

# CORRELAÇÃO COM VARIÁVEL ALVO prod_ton
# 1. Definir quais variáveis queremos ver a relação com 'prod_ton'
# Pegamos apenas as colunas que realmente existem no seu dataframe para evitar o KeyError
colunas_interesse = ['prod_ton', 'Precipitacao_Media', 'Temp_Max_Media', 'Total_Focos', 'VPD_Medio', 'Umidade_Relativa_Media']
colunas_presentes = [col for col in colunas_interesse if col in df_analise.columns]

# 2. Gerar a Matriz de Correlação
plt.figure(figsize=(10, 6))
sns.heatmap(df_analise[colunas_presentes].corr(), annot=True, cmap='RdYlGn', fmt=".2f")
plt.title("Correlação entre Produção de Castanha e Variáveis Climáticas")
plt.show()

# 3. Gráficos de Dispersão para as duas variáveis mais importantes
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Produção vs Chuva
if 'Precipitacao_Media' in df_analise.columns:
    sns.regplot(ax=axes[0], x='Precipitacao_Media', y='prod_ton', data=df_analise, color='blue')
    axes[0].set_title('Produção vs Precipitação')

# Produção vs Calor (ou Fogo)
if 'Temp_Max_Media' in df_analise.columns:
    sns.regplot(ax=axes[1], x='Temp_Max_Media', y='prod_ton', data=df_analise, color='red')
    axes[1].set_title('Produção vs Temperatura Máxima')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Relação Produção vs Precipitação
sns.regplot(ax=axes[0], x='Precipitacao_Media', y='prod_ton', data=df_analise, color='blue')
axes[0].set_title('Produção vs Precipitação Média')
axes[0].set_xlabel('Precipitação (mm)')
axes[0].set_ylabel('Produção (ton)')

# Relação Produção vs Focos de Queimada
sns.regplot(ax=axes[1], x='Total_Focos', y='prod_ton', data=df_analise, color='red')
axes[1].set_title('Produção vs Total de Focos de Queimada')
axes[1].set_xlabel('Total de Focos')
axes[1].set_ylabel('Produção (ton)')

plt.tight_layout()
plt.show()

# 1. Fazemos uma cópia para segurança
df_features_clean = df_features.copy()

# 2. Identificamos as colunas que deveriam ser números (quase todas)
cols_para_corrigir = [col for col in df_features_clean.columns if col not in ['Data', 'UF', 'ano']]

# 3. O SEGREDO: pd.to_numeric com errors='coerce'
# Isso transforma qualquer "-" ou "---" em NaN (nulo numérico)
for col in cols_para_corrigir:
    df_features_clean[col] = pd.to_numeric(df_features_clean[col], errors='coerce')

# 4. Verifique agora: o describe deve mostrar estatísticas reais (mean, std) e não 'unique'
print(df_features_clean[cols_para_corrigir].describe())

# Agrupando por ano (agora as médias vão funcionar ignorando os NaNs)
df_features_ano = df_features_clean.groupby("ano")[cols_para_corrigir].mean().reset_index()

# Criando o dataframe de análise cruzando com a produção
df_analise = pd.merge(df_castanha[['ano', 'prod_ton']], df_features_ano, on='ano')

# Gerando a correlação dos rios
colunas_rios = [col for col in df_analise.columns if any(char.isdigit() for char in col) and col != 'ano']
corr_rios = df_analise[['prod_ton'] + colunas_rios].corr()['prod_ton'].drop('prod_ton').dropna().sort_values()

# Plotando se houver dados
if not corr_rios.empty:
    plt.figure(figsize=(10, 8))
    corr_rios.plot(kind='barh', color='skyblue')
    plt.title("Relação Produção vs Nível dos Rios (Dados Limpos)")
    plt.show()
else:
    print("Mesmo após a limpeza, esses rios não têm dados suficientes para correlação.")
